### ISSUE TITLE
Steady state distribution of Krusell-Smith model

### ISSUE THREAD

**Issue by mikkelpm** [shade-econ/sequence-jacobian#1]
I have two comments on the steady state in the Krusell-Smith model:

1. When I run the Krusell-Smith Jupyter notebook, I obtain substantially negative values in the `D` matrix. I think it is due to the second-to-last line in `interpolate_coord`:
https://github.com/shade-econ/sequence-jacobian/blob/a493e9706026bc3f7c528b4e8c0720a23e6e4cfd/utils.py#L68
If an element of `xq` exceeds the largest value in `x`, then the above line will return a negative weight `xqpi`. This is easy to fix by censoring the weights below at 0.
2. The default value of `amax` should probably be set substantially larger (like 60):
https://github.com/shade-econ/sequence-jacobian/blob/a493e9706026bc3f7c528b4e8c0720a23e6e4cfd/krusell_smith.py#L90
https://github.com/shade-econ/sequence-jacobian/blob/a493e9706026bc3f7c528b4e8c0720a23e6e4cfd/krusell_smith.ipynb#L229
With the current value `amax=20`, the conditional asset distribution is almost a point mass at `amax` for individuals with high idiosyncratic productivity.

Thanks so much for providing this fantastic toolkit!

Best,
Mikkel

**Comment by mrognlie** [comment]
Hi Mikkel,

Very good catch, thanks so much for pointing this out! The `amax=20` was a hangover from the original case where we had a traditional two-state Krusell-Smith calibration, and we forgot to change that default when we changed the default dispersion of the income process. We just changed it to `amax=200`.

As you pointed out, the negative entries in `D` were a consequence of `amax` being too low: the default behavior when the policy overshoots the grid is a kind of linear extrapolation, where the highest gridpoint in `D` gets lots of positive mass and the second-highest gets lots of negative mass. Conditional on overshooting, this was intentional: it ensures that the continuous policy `a` aggregated according to today's `D` equals the actual assets in tomorrow's `D`, whereas we would lose some assets if we censored. But, of course, we really never want overshooting to happen -- maybe we should enable by default a check to report when this happens.

We pushed this quick change to master, but I should also mention that we are about to do a big update, which you can see in progress on the develop branch and which we'll merge into master in a couple days.

Thanks again!
Matt
