### ISSUE TITLE
simple blocks and custom function

### ISSUE THREAD

**Issue by azinoma** [shade-econ/sequence-jacobian#11]
Dear all,

thank you very much for this amazing method *and* library, I am a big fan.
I was wondering, whether it is possible to have a simple block, where we can call some arbitrary custom function.
I am thinking of, e.g. solving a nonlinear equation inside a simple block, but all within a single time period, so that a solved block, if I understand correctly, shouldn't be necessary.
When I try, the steady state solves just fine, but I am getting errors related to `AccumulatedDerivative` later on.
I also tried to circumvent the need for `.apply(np.log)`, by using `from numpy import log as log`, but this also throws a similar error (`loop of ufunc does not support argument 0 of type AccumulatedDerivative which has no callable log method`).

One work around I was thinking of would be to disguise the simple block as an artificial het block.

It may well be that I am totally misunderstanding something, any advice would be appreciated.

Many greetings,
Marlon

**Comment by caimichael** [comment]
Hi Marlon,

So sorry for the late response! We do have functionality that can compute derivatives of arbitrary custom functions in `SimpleBlock`s. Basically the method `.apply` can take an arbitrary function (with other positional arguments specified as kwargs - can't actually remember why I set it this way as opposed to as args) and will compute its derivative using numerical differentiation (when using the methods to compute Jacobians).

You actually have to use `.apply` for any function that's not a simple arithmetic function because we implemented `AccumulatedDerivative` to be able to behave as an auto-differentiator and hence it has to know which functions require special handling for computing derivatives.

Hope this helps!
Michael
